server.port=9003

spring.application.name=kafka-monitor
spring.kafka.bootstrap-servers=52.23.9.29:29092,52.23.9.29:39092,52.23.9.29:49092

app.kafka.topic-ubicaciones=ubicaciones
app.kafka.topic-horarios=horarios

spring.kafka.consumer.group-id=kafka-monitor-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

spring.datasource.username=BDUser_26
spring.datasource.password=BDUser.26JC#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.url=jdbc:oracle:thin:@afjc_high
spring.datasource.hikari.data-source-properties.oracle.net.TNS_ADMIN=C:/Wallet/Wallet_AFJC