INSERT INTO KAFKA_RESUMEN_VEHICULO (
  CODIGO_UNIDAD,
  TS_INI, LAT_INI, LON_INI,
  TS_FIN, LAT_FIN, LON_FIN,
  ATRASO_PROM, ATRASO_MAX,
  MINUTOS_REPORTANDO, TOTAL_PINGS,
  FECHA_CREACION
)
WITH
Z AS (
  SELECT
    TRUNC(CAST(SYSTIMESTAMP AT TIME ZONE 'America/Santiago' AS DATE)) AS INI_CL,
    TRUNC(CAST(SYSTIMESTAMP AT TIME ZONE 'America/Santiago' AS DATE)) + 1 AS FIN_CL
  FROM dual
),
U AS (
  SELECT
    CODIGO_UNIDAD,
    FECHA_EVENTO,
    LATITUD,
    LONGITUD,
    TRUNC(
      FROM_TZ(CAST(FECHA_EVENTO AS TIMESTAMP), 'UTC')
      AT TIME ZONE 'America/Santiago',
      'MI'
    ) AS MINUTO,
    ROW_NUMBER() OVER (PARTITION BY CODIGO_UNIDAD ORDER BY FECHA_EVENTO)       AS RN_ASC,
    ROW_NUMBER() OVER (PARTITION BY CODIGO_UNIDAD ORDER BY FECHA_EVENTO DESC)  AS RN_DESC
  FROM KAFKA_UBICACION
  WHERE FECHA_EVENTO >= (SELECT INI_CL FROM Z)
    AND FECHA_EVENTO <  (SELECT FIN_CL FROM Z)
),
PUNTO_INI AS (
  SELECT
    CODIGO_UNIDAD,
    FROM_TZ(CAST(FECHA_EVENTO AS TIMESTAMP), 'UTC')
      AT TIME ZONE 'America/Santiago' AS TS_INI,
    LATITUD AS LAT_INI,
    LONGITUD AS LON_INI
  FROM U
  WHERE RN_ASC = 1
),
PUNTO_FIN AS (
  SELECT
    CODIGO_UNIDAD,
    FROM_TZ(CAST(FECHA_EVENTO AS TIMESTAMP), 'UTC')
      AT TIME ZONE 'America/Santiago' AS TS_FIN,
    LATITUD AS LAT_FIN,
    LONGITUD AS LON_FIN
  FROM U
  WHERE RN_DESC = 1
),
MINUTOS AS (
  SELECT
    CODIGO_UNIDAD,
    COUNT(DISTINCT MINUTO) AS MINUTOS_REPORTANDO,
    COUNT(*) AS TOTAL_PINGS
  FROM U
  GROUP BY CODIGO_UNIDAD
),
RETRASO AS (
  SELECT
    CODIGO_UNIDAD,
    AVG(NVL(RETRASO_MIN,0)) AS ATRASO_PROM,
    MAX(NVL(RETRASO_MIN,0)) AS ATRASO_MAX
  FROM KAFKA_HORARIO
  WHERE FECHA_EVENTO >= (SELECT INI_CL FROM Z)
    AND FECHA_EVENTO <  (SELECT FIN_CL FROM Z)
  GROUP BY CODIGO_UNIDAD
)
SELECT
  m.CODIGO_UNIDAD,
  pi.TS_INI, pi.LAT_INI, pi.LON_INI,
  pf.TS_FIN, pf.LAT_FIN, pf.LON_FIN,
  ROUND(NVL(r.ATRASO_PROM,0), 2),
  NVL(r.ATRASO_MAX,0),
  m.MINUTOS_REPORTANDO,
  m.TOTAL_PINGS,
  SYSTIMESTAMP
FROM MINUTOS m
LEFT JOIN PUNTO_INI pi ON pi.CODIGO_UNIDAD = m.CODIGO_UNIDAD
LEFT JOIN PUNTO_FIN pf ON pf.CODIGO_UNIDAD = m.CODIGO_UNIDAD
LEFT JOIN RETRASO r    ON r.CODIGO_UNIDAD = m.CODIGO_UNIDAD
ORDER BY m.CODIGO_UNIDAD